package se.inera.intyg.common.support.modules.support.facade.dto;

public enum CertificateEventTypeDTO {
    CREATED,
    DELETED,
    LOCKED,
    READY_FOR_SIGN,
    SIGNED,
    SENT,
    AVAILABLE_FOR_PATIENT,
    INCOMING_MESSAGE,
    INCOMING_MESSAGE_HANDLED,
    OUTGOING_MESSAGE,
    OUTGOING_MESSAGE_HANDLED,
    INCOMING_MESSAGE_REMINDER,
    REQUEST_FOR_COMPLEMENT,
    REVOKED,
    REPLACED,
    REPLACES,
    COMPLEMENTED,
    EXTENDED,
    CREATED_FROM,
    COPIED_BY,
    COPIED_FROM,
    RELATED_CERTIFICATE_REVOKED
}
